=== StateSpaceModels/ssm/json-schema/model-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "SSM model",
  "description": "Description of a state space model following the grammar of the SSM inference package",
  "definitions": {
    "require": {
      "type": "object",
      "properties": {
        "datapackage": {
          "type": "string"
        },
        "resource": {
          "type": "string"
        },
        "fields": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "populations": {
      "type": "array",
      "description": "Grouping of the state variables comprised in your compartmental model. For each group, provide a name and the list of corresponding states. By adding an optional remainder field, you will ensure the population size remains positive.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "composition": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "remainder": {
            "type": "object",
            "description": "Following this instruction, the value of the remainder variable at every time will be determined by the size of the population minus the sum of the other compartments. Note that SSM will discard scenarios where this variable becomes negative.",
            "properties": {
              "name": {
                "type": "string"
              },
              "pop_size": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "pop_size"
            ]
          }
        },
        "required": [
          "name",
          "composition"
        ]
      }
    },
    "reactions": {
      "type": "array",
      "description": "Description of the dynamics of your compartmental model. We only consider density-dependent reactions: each rate will be multiplied by the size of the compartment individuals are leaving. See the accumulators and white_noise optional fields for additional options.",
      "items": {
        "type": "object",
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          },
          "rate": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "white_noise": {
            "type": "object",
            "description": "In order to cope with the absence or mis-specification of environmental factors in the model, you can multiply the rate of each reaction by a white gamma noise. To correlate these noises, use the same name. For more information, see Breto et al. 2009, Time series analysis via mechanistic models.",
            "properties": {
              "name": {
                "type": "string"
              },
              "sd": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "sd"
            ]
          },
          "accumulators": {
            "type": "array",
            "description": "When your are monitoring or fitting the integrated flow of a given reaction, you can store it in one or several variables defined in this list. If a given flow variable is repeated in several reactions, it will correspond of the sum of the flows of these reactions.",
            "items": {
              "type": "string"
            }
          },
          "keywords": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "from",
          "to",
          "rate"
        ]
      }
    },
    "sde": {
      "type": "object",
      "description": "System of stochastic differential equations, defined by their drift vector and dispersion matrix",
      "properties": {
        "drift": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "State variable which dynamic is determined by this line of the system."
              },
              "f": {
                "type": [
                  "number",
                  "string"
                ],
                "description": "Deterministic component of the equation."
              },
              "transformation": {
                "type": "string",
                "description": "In case you want to express the equation in terms of a function of X and avoid applying the Ito formula."
              }
            },
            "required": [
              "name",
              "f"
            ]
          }
        },
        "dispersion": {
          "type": "array",
          "description": "Dispersion matrix L. It needs to have as many rows as objects in drifts, and as many colums as independent sources of noise.",
          "items": {
            "type": "array",
            "items": {
              "type": [
                "number",
                "string"
              ]
            }
          }
        }
      },
      "required": [
        "drift",
        "dispersion"
      ]
    },
    "ode": {
      "type": "array",
      "description": "System of ordinary differential equations.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "State variable which dynamic is determined by this line of the system."
          },
          "f": {
            "type": [
              "number",
              "string"
            ],
            "description": "Deterministic component of the equation."
          },
          "transformation": {
            "type": "string",
            "description": "In case you want to express the equation in terms of a function of X and avoid applying the Ito formula."
          }
        },
        "required": [
          "name",
          "f"
        ]
      }
    },
    "observations": {
      "type": "array",
      "description": "Name each of the observed time series, determine when observations started to be collected and what is the distribution of the observation process.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "start": {
            "type": "string",
            "format": "date-time"
          },
          "distribution": {
            "type": "string"
          },
          "mean": {
            "type": "string"
          },
          "sd": {
            "type": "string"
          },
          "n": {
            "type": "string"
          },
          "p": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "start",
          "distribution"
        ]
      }
    },
    "data": {
      "type": "array",
      "description": "Link each of the observed variables to a data resource.",
      "items": {
        "type": "object",
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "require": {
                "$ref": "#/definitions/require"
              },
              "transformation": {
                "description": "When the parameters used in the model are functions of the data resources, specify the relation here.",
                "type": "string"
              }
            },
            "required": [
              "name",
              "require"
            ]
          }
        ]
      }
    },
    "inputs": {
      "type": "array",
      "description": "Link each of the parameters or covariates at stake in your model to a data resource.",
      "items": {
        "type": "object",
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "require": {
                "$ref": "#/definitions/require"
              },
              "transformation": {
                "description": "When the parameters used in the model are functions of the data resources, specify the relation here.",
                "type": "string"
              },
              "to_resource": {
                "description": "In order to make predictions after fitting your data, specify how to invert the transformation relation at a later time than t0.",
                "type": "string"
              }
            },
            "required": [
              "name"
            ]
          }
        ]
      }
    }
  }
}

=== StateSpaceModels/ssm/examples/noise/ssm.json
{
  "data": [
    {
      "name": "all_CDC_inc_out",
      "require": {"path": "data/data.csv", "fields": ["date", "all_CDC_inc_out"]}
    },
    {
      "name": "all_google_inc_out",
      "require": {"path": "data/data.csv", "fields": ["date", "all_google_inc_out"]}
    },
    {
      "name": "paris_CDC_prev",
      "require": {"path": "data/data.csv", "fields": ["date",  "paris_CDC_prev"]}
    },
    {
      "name": "nyc_CDC_inc",
      "require": {"path": "data/data.csv", "fields": ["date", "nyc_CDC_inc"]}
    }
  ],

  "inputs": [
    {
      "name": "N_nyc",
      "require": {"path": "data/N.csv", "fields": ["date", "nyc"]}
    },
    {
      "name": "N_paris",
      "require": {"path": "data/N.csv", "fields": ["date", "paris"]}
    },
    {
      "name": "mu_b_paris",
      "require": {"path": "data/mu_b.csv", "fields": ["date", "paris"]}
    },
    {
      "name": "mu_b_nyc",
      "require": {"path": "data/mu_b.csv", "fields": ["date", "nyc"]}
    },
    {
      "name": "mu_d_paris",
      "require": {"path": "data/mu_d.csv", "fields": ["date", "paris"]}
    },
    {
      "name": "mu_d_nyc",
      "require": {"path": "data/mu_d.csv", "fields": ["date", "nyc"]}
    },
    {
      "name": "prop_all_CDC_inc",
      "require": {"path": "data/prop.csv", "fields": ["date", "all_CDC_inc"]}
    },
    {
      "name": "prop_paris_CDC_prev",
      "require": {"path": "data/prop.csv", "fields": ["date", "paris_CDC_prev"]}
    },
    {
      "name": "prop_all_google_inc",
      "require": {"path": "data/prop.csv", "fields": ["date", "all_google_inc"]}
    },
    {
      "name": "prop_nyc_CDC_inc",
      "require": {"path": "data/prop.csv", "fields": ["date", "nyc_CDC_inc"]}
    },

    {
      "name": "S_paris",
      "description": "Number of susceptible",
      "require": {"path": "data/pr_S_paris.json", "name": "pr_S_paris"},
      "transformation": "pr_S_paris*N_paris",
      "to_resource": "S_paris/N_paris"
    },
    {
      "name": "S_nyc",
      "description": "Number of susceptible",
      "transformation": "pr_S_paris*N_nyc"
    },
    {
      "name": "I_paris",
      "description": "Number of infectious",
      "require": {"path": "data/pr_I_paris.json", "name": "pr_I_paris"},
      "transformation": "pr_I_paris*N_paris",
      "to_resource": "I_paris/N_paris"
    },
    {
      "name": "I_nyc",
      "description": "Number of susceptible",
      "transformation": "pr_I_paris*N_nyc"
    },
    {
      "name": "r0_paris",
      "description": "basic reproduction number",
      "require": {"path": "data/r0_paris.json"}
    },
    {
      "name": "r0_nyc",
      "description": "basic reproduction number",
      "require": {"path": "data/r0_nyc.json"}
    },
    {
      "name": "v",
      "description": "recovery rate",
      "require": {"path": "data/pr_v.json", "name": "pr_v"},
      "transformation": "1/pr_v",
      "to_resource": "1/v"
    },
    {
      "name": "sto",
      "description": "noise intensity",
      "require": {"path": "data/sto.json"}
    },
    {
      "name": "rep_all_CDC_inc",
      "description": "reporting rate",
      "require": {"path": "data/rep_all_CDC_inc.json"}
    },
    {
      "name": "rep_all_google_inc",
      "description": "reporting rate",
      "transformation": "rep_all_CDC_inc"       
    },
    {
      "name": "rep_nyc_CDC_inc",
      "description": "reporting rate",
      "transformation": "rep_all_CDC_inc"
    },
    {
      "name": "rep_paris_CDC_prev",
      "description": "reporting rate",
      "transformation": "rep_all_CDC_inc"
    },
    {
      "name": "phi",
      "description": "over-dispertion",
      "require": {"path": "data/phi.json"}
    }
  ],

  "populations": [
    {"name": "paris", "composition": ["S_paris", "I_paris", "R_paris"], "remainder": {"name": "R_paris", "pop_size": "N_paris"}},
    {"name": "nyc",   "composition": ["S_nyc", "I_nyc", "R_nyc"],       "remainder": {"name": "R_nyc",   "pop_size": "N_nyc"}}
  ],
  
  "reactions": [
    {"from": "U",       "to": "S_paris", "rate": "mu_b_paris*N_paris",         "description":"birth"},
    {"from": "U",       "to": "S_nyc",   "rate": "mu_b_nyc*N_nyc",             "description":"birth"},

    {"from": "S_paris", "to": "I_paris", "rate": "r0_paris/N_paris*v*I_paris", "description":"infection", "white_noise": {"name":"noise_SI", "sd": "sto"}},
    {"from": "S_nyc",   "to": "I_nyc",   "rate": "r0_nyc/N_nyc*v*I_nyc",       "description":"infection", "accumulators": ["nyc_inc"], "white_noise": {"name":"noise_SI2", "sd": "sto"}},

    {"from": "I_paris", "to": "R_paris", "rate": "correct_rate(v)",            "description":"recovery", "accumulators": ["all_inc_out"]},
    {"from": "I_nyc",   "to": "R_nyc",   "rate": "correct_rate(v)",            "description":"recovery", "accumulators": ["all_inc_out"]},

    {"from": "S_paris", "to": "U",       "rate": "mu_d_paris",                 "description":"death"},
    {"from": "S_nyc",   "to": "U",       "rate": "mu_d_nyc",                   "description":"death"},

    {"from": "I_paris", "to": "U",       "rate": "mu_d_paris",                 "description":"death", "accumulators": ["all_inc_out"]},
    {"from": "I_nyc",   "to": "U",       "rate": "mu_d_nyc",                   "description":"death", "accumulators": ["all_inc_out"]},
    {"from": "R_paris", "to": "U",       "rate": "mu_d_paris",                 "description":"death"},
    {"from": "R_nyc",   "to": "U",       "rate": "mu_d_nyc",                   "description":"death"}
  ],

  "observations": [
    {
      "name": "all_CDC_inc_out",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_all_CDC_inc * prop_all_CDC_inc * all_inc_out",
      "sd": "sqrt(rep_all_CDC_inc * ( 1.0 - rep_all_CDC_inc ) * prop_all_CDC_inc * all_inc_out + pow(rep_all_CDC_inc * phi * prop_all_CDC_inc * all_inc_out, 2) )"
    },
    {
      "name": "all_google_inc_out",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_all_google_inc * prop_all_google_inc * all_inc_out",
      "sd": "sqrt(rep_all_google_inc * ( 1.0 - rep_all_google_inc ) * prop_all_google_inc * all_inc_out + pow(rep_all_google_inc * phi * prop_all_google_inc * all_inc_out, 2) )"
    },
    {
      "name": "paris_CDC_prev",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_paris_CDC_prev * prop_paris_CDC_prev * I_paris",
      "sd": "sqrt(rep_paris_CDC_prev * ( 1.0 - rep_paris_CDC_prev ) * prop_paris_CDC_prev * I_paris + pow(rep_paris_CDC_prev * phi * prop_paris_CDC_prev * I_paris, 2) )"
    },

    {
      "name": "nyc_CDC_inc",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_nyc_CDC_inc * prop_nyc_CDC_inc * nyc_inc",
      "sd": "sqrt(rep_nyc_CDC_inc * ( 1.0 - rep_nyc_CDC_inc ) * prop_nyc_CDC_inc * nyc_inc + pow(rep_nyc_CDC_inc * phi * prop_nyc_CDC_inc * nyc_inc, 2) )"
    }
  ]
}

=== StateSpaceModels/ssm/examples/foo/ssm.json
{
  "data": [
    {
      "name": "all_CDC_inc",
      "require": { "path": "data/data.csv", "fields": ["date", "all_CDC_inc"] }
    },
    {
      "name": "paris_CDC_prev",
      "require": { "path": "data/data.csv", "fields": ["date", "paris_CDC_prev"] }
    },
    {
      "name": "all_google_inc",
      "require": { "path": "data/data.csv", "fields": ["date", "all_google_inc"] }
    },
    {
      "name": "nyc_CDC_inc",
      "require": { "path": "data/data.csv", "fields": ["date", "nyc_CDC_inc"] }
    }
  ],

  "inputs": [
    {
      "name": "N_nyc",
      "require": { "path": "data/N.csv", "fields": ["date", "nyc"] }
    },
    {
      "name": "N_paris",
      "require": { "path": "data/N.csv", "fields": ["date", "paris"] }
    },
    {
      "name": "mu_b_paris",
      "require": { "path": "data/mu_b.csv", "fields": ["date", "paris"] }
    },
    {
      "name": "mu_b_nyc",
      "require": { "path": "data/mu_b.csv", "fields": ["date", "nyc"] }
    },
    {
      "name": "mu_d_paris",
      "require": { "path": "data/mu_d.csv", "fields": ["date", "paris"] }
    },
    {
      "name": "mu_d_nyc",
      "require": { "path": "data/mu_d.csv", "fields": ["date", "nyc"] }
    },
    {
      "name": "prop_all_CDC_inc",
      "require": { "path": "data/prop.csv", "fields": ["date", "all_CDC_inc"] }
    },
    {
      "name": "prop_paris_CDC_prev",
      "require": { "path": "data/prop.csv", "fields": ["date", "paris_CDC_prev"] }
    },
    {
      "name": "prop_all_google_inc",
      "require": { "path": "data/prop.csv", "fields": ["date", "all_google_inc"] }
    },
    {
      "name": "prop_nyc_CDC_inc",
      "require": { "path": "data/prop.csv", "fields": ["date","nyc_CDC_inc"] }
    },


    {
      "name": "S_paris",
      "description": "Number of susceptible",
      "require": {"name": "pr_S_paris", "path": "data/pr_S_paris.json"},
      "transformation": "pr_S_paris*N_paris",
      "to_resource": "S_paris/N_paris"
    },
    {
      "name": "S_nyc",
      "description": "Number of susceptible",
      "transformation": "pr_S_paris*N_nyc"
    },
    {
      "name": "I_paris",
      "description": "Number of infectious",
      "keywords": ["infectious"],
      "require": {"name": "pr_I_paris", "path": "data/pr_I_paris.json" },
      "transformation": "pr_I_paris*N_paris",
      "to_resource": "I_paris/N_paris"
    },
    {
      "name": "I_nyc",
      "description": "Number of infectious",
      "keywords": ["infectious"],
      "require": {"name": "pr_I_nyc", "path": "data/pr_I_nyc.json"},
      "transformation": "pow(10, -pr_I_nyc) * N_nyc",
      "to_resource": "-log(I_nyc)/(log(10)*N_nyc)"
    },
    {
      "name": "r0_paris",
      "description": "basic reproduction number",
      "require": {"name": "r0_paris", "path": "data/r0_paris.json"}
    },
    {
      "name": "r0_nyc",
      "description": "basic reproduction number",
      "require": {"name": "r0_nyc", "path": "data/r0_nyc.json"}
    },
    {
      "name": "vol",
      "description": "volatility of the diffusion",
      "require": {"name": "vol", "path": "data/vol.json"}
    },
    {
      "name": "v",
      "description": "recovery rate",
      "require": {"name": "pr_v", "path": "data/pr_v.json"},
      "transformation": "1/pr_v",
      "to_resource": "1/v"
    },
    {
      "name": "sto",
      "description": "noise intensity",
      "require": {"name": "sto", "path": "data/sto.json"}
    },
    {
      "name": "rep_all_CDC_inc",
      "description": "reporting rate",
      "require": {"name": "rep_all_CDC_inc", "path": "data/rep_all_CDC_inc.json"}
    },
    {
      "name": "rep_paris_CDC_prev",
      "description": "reporting rate",
      "require": {"name": "rep_paris_CDC_prev", "path": "data/rep_paris_CDC_prev.json"}
    },
    {
      "name": "rep_all_google_inc",
      "description": "reporting rate",
      "require": {"name": "rep_all_google_inc", "path": "data/rep_all_google_inc.json"}
    },
    {
      "name": "rep_nyc_CDC_inc",
      "description": "reporting rate",
      "require": {"name": "rep_nyc_CDC_inc", "path": "data/rep_nyc_CDC_inc.json"}
    },
    {
      "name": "phi",
      "description": "over-dispertion",
      "require": {"name": "phi", "path": "data/phi.json"}
    }
  ],

  "populations": [
    {"name": "paris", "composition": ["S_paris", "I_paris", "R_paris"], "remainder": {"name": "R_paris", "pop_size": "N_paris"}},
    {"name": "nyc",   "composition": ["S_nyc", "I_nyc", "R_nyc"],       "remainder": {"name": "R_nyc",   "pop_size": "N_nyc"}}
  ],

  "reactions": [
    {"from": "U",       "to": "S_nyc",   "rate": "mu_b_nyc*N_nyc",             "description":"birth"},
    {"from": "U",       "to": "S_paris", "rate": "mu_b_paris*N_paris",         "description":"birth"},

    {"from": "S_nyc",   "to": "I_nyc",   "rate": "r0_nyc/N_nyc*v*I_nyc",       "description":"infection", "keywords": ["transmission"], "accumulators": ["Inc_in_nyc"], "white_noise": {"name": "noise_SI", "sd": "sto"}},
    {"from": "S_paris", "to": "I_paris", "rate": "r0_paris/N_paris*v*I_paris", "description":"infection", "keywords": ["transmission"]},

    {"from": "I_nyc",   "to": "R_nyc",   "rate": "correct_rate(v)",            "description":"recovery", "accumulators": ["Inc_out"]},
    {"from": "I_paris", "to": "R_paris", "rate": "correct_rate(v)",            "description":"recovery", "accumulators": ["Inc_out"]},

    {"from": "S_nyc",   "to": "U",       "rate": "mu_d_nyc",                   "description":"death"},
    {"from": "S_paris", "to": "U",       "rate": "mu_d_paris",                 "description":"death"},

    {"from": "I_nyc",   "to": "U",       "rate": "mu_d_nyc",                   "description":"death", "accumulators": ["Inc_out"]},
    {"from": "I_paris", "to": "U",       "rate": "mu_d_paris",                 "description":"death", "accumulators": ["Inc_out"]}
  ],

  "sde": {
    "drift": [
      {"name": "r0_paris", "f": 0.0, "transformation": "log(r0_paris)"},
      {"name": "r0_nyc",   "f": 0.0, "transformation": "log(r0_nyc)"}
    ],
    "dispersion":[
      ["vol", 0],
      [0, "vol"]
    ]
  },

  "observations": [
    {
      "name": "all_CDC_inc",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_all_CDC_inc * prop_all_CDC_inc * Inc_out",
      "sd": "sqrt(rep_all_CDC_inc * ( 1.0 - rep_all_CDC_inc ) * prop_all_CDC_inc * Inc_out + pow(rep_all_CDC_inc * phi * prop_all_CDC_inc * Inc_out, 2) )"
    },
    {
      "name": "paris_CDC_prev",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_paris_CDC_prev * prop_paris_CDC_prev * I_paris",
      "sd": "sqrt(rep_paris_CDC_prev * ( 1.0 - rep_paris_CDC_prev ) * prop_paris_CDC_prev * I_paris + pow(rep_paris_CDC_prev * phi * prop_paris_CDC_prev * I_paris, 2) )"
    },
    {
      "name": "all_google_inc",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_all_google_inc * prop_all_google_inc * Inc_out",
      "sd": "sqrt(rep_all_google_inc * ( 1.0 - rep_all_google_inc ) * prop_all_google_inc * Inc_out + pow(rep_all_google_inc * phi * prop_all_google_inc * Inc_out, 2) )"
    },
    {
      "name": "nyc_CDC_inc",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep_nyc_CDC_inc * prop_nyc_CDC_inc * Inc_in_nyc",
      "sd": "sqrt(rep_nyc_CDC_inc * ( 1.0 - rep_nyc_CDC_inc ) * prop_nyc_CDC_inc * Inc_in_nyc + pow(rep_nyc_CDC_inc * phi * prop_nyc_CDC_inc * Inc_in_nyc, 2) )"
    }
  ]
}

=== StateSpaceModels/ssm/examples/tutorial/ssm.json
{
  "data": [
    {
      "name": "cases",
      "require": { "path": "data/data.csv", "fields": ["date", "cases"] }
    }
  ],

  "inputs": [
    {
      "name": "r0",
      "description": "Basic reproduction number",
      "require": { "name": "r0", "path": "data/r0.json" }
    },
    {
      "name": "v",
      "description": "Recovery rate",
      "require": { "name":  "pr_v", "path": "data/pr_v.json" },
      "transformation": "1/pr_v",
      "to_resource": "1/v"
    },
    {
      "name": "S",
      "description": "Number of susceptible",
      "require": { "name": "S", "path": "data/S.json" }
    },
    {
      "name": "I",
      "description": "Number of infectious",
      "require": { "name": "I", "path": "data/I.json" }
    },
    {
      "name": "R",
      "description": "Number of recovered",
      "require": { "name": "R", "path": "data/R.json" }
    },
    {
      "name": "rep",
      "description": "Reporting rate",
      "require": { "name": "rep", "path": "data/rep.json" }
    }
  ],

  "populations": [
    {"name": "NYC", "composition": ["S", "I", "R"]}
  ],

  "reactions": [
    {"from": "S", "to": "I", "rate": "r0/(S+I+R)*v*I", "description": "infection", "accumulators": ["Inc"]},
    {"from": "I", "to": "R", "rate": "v", "description":"recovery"}
  ],

  "observations": [
    {
      "name": "cases",
      "start": "2012-07-26",
      "distribution": "discretized_normal",
      "mean": "rep * Inc",
      "sd": "sqrt(rep * ( 1.0 - rep ) * Inc )"
    }
  ]
}
